version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: loja_db_server
    environment:
      - POSTGRES_USER=loja
      - POSTGRES_PASSWORD=loja_pass
      - POSTGRES_DB=loja_db  # Mantenha este nome, mas garanta que a APP use o mesmo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - loja-veloz-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loja -d loja_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway:
    build: ./src/gateway
    image: john/loja-veloz-gateway:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=loja
      - DB_PASS=loja_pass
      - DB_NAME=loja_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - loja-veloz-net

  pedidos:
    build: ./src/pedidos
    image: john/loja-veloz-pedidos:latest
    environment:
      - DB_HOST=db
      - DB_USER=loja
      - DB_PASS=loja_pass
      - DB_NAME=loja_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - loja-veloz-net

  pagamentos:
    build: ./src/pagamentos
    image: john/loja-veloz-pagamentos:latest
    environment:
      - DB_HOST=db
      - DB_USER=loja
      - DB_PASS=loja_pass
      - DB_NAME=loja_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - loja-veloz-net

  estoque:
    build: ./src/estoque
    image: john/loja-veloz-estoque:latest
    environment:
      - DB_HOST=db
      - DB_USER=loja
      - DB_PASS=loja_pass
      - DB_NAME=loja_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - loja-veloz-net

volumes:
  postgres_data:

networks:
  loja-veloz-net:
    driver: bridge