apiVersion: v1
kind: Service
metadata:
  name: loja-veloz-gateway
  labels:
    app: loja-veloz-gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: loja-veloz-pedidos
  labels:
    app: loja-veloz-pedidos
spec:
  type: ClusterIP
  selector:
    app: pedidos
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: loja-veloz-pagamentos
  labels:
    app: loja-veloz-pagamentos
spec:
  type: ClusterIP
  selector:
    app: pagamentos
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: loja-veloz-estoque
  labels:
    app: loja-veloz-estoque
spec:
  type: ClusterIP
  selector:
    app: estoque
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
